### ISSUE TITLE
Add support for tvOS

### ISSUE THREAD

**Issue by ghost** [MauriceArikoglu/SwiftCal#6]
Could you please add tvOS to the podspecs file

**Comment by sanketfirodiya** [comment]
@ptr-is submitting a pr might be faster if you have already made/tested the change :)

**Comment by MauriceArikoglu** [comment]
@ptr-is please do as @sanketfirodiya suggested

**Comment by MauriceArikoglu** [comment]
Closed because user is not with us anymore
